export const quotes = [
    "The secret of getting ahead is getting started.",
    "Focus on being productive instead of busy.",
    "Small daily improvements are the key to staggering long-term results.",
    "Don't watch the clock; do what it does. Keep going.",
    "The only way to do great work is to love what you do.",
    "Your future is created by what you do today, not tomorrow.",
    "It always seems impossible until it's done.",
    "Success is the sum of small efforts repeated day in and day out.",
    "The more you thank life, the more it gives you.",
    "Believe you can and you're halfway there.",
    "What we think, we become.",
    "Do what you can, with what you have, where you are.",
    "Start where you are. Use what you have. Do what you can.",
    "You don't have to be great to start, but you have to start to be great.",
    "Discipline is the bridge between goals and accomplishment.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Action is the foundational key to all success.",
    "Strive not to be a success, but rather to be of value.",
    "Energy and persistence conquer all things.",
    "Well done is better than well said.",
    "A year from now you may wish you had started today.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Productivity is never an accident. It is always the result of commitment to excellence.",
    "Stay focused, go after your dreams and keep moving toward your goals.",
    "You are never too old to set another goal or to dream a new dream.",
    "The way to get started is to quit talking and begin doing.",
    "Don't be afraid to give up the good to go for the great.",
    "In the middle of every difficulty lies opportunity.",
    "Everything you've ever wanted is on the other side of fear.",
    "Dream big. Start small. Act now.",
    "The only limit is your mind.",
    "Simplicity is the ultimate sophistication.",
    "Make each day your masterpiece.",
    "Progress, not perfection.",
    "Deep work is the superpower of the 21st century.",
];

export function getRandomQuote(): string {
    return quotes[Math.floor(Math.random() * quotes.length)];
}
